using Content.Shared.SS220.MineralTrade.Protos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.MineralTrade.UI;

[GenerateTypedNameReferences]
public sealed partial class MineralTradeItemCard : PanelContainer
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    public Action<string>? OnBuy;
    public Action<string>? OnSell;
    private EntityUid? _materialInstance;
    public bool CheckoutCard = false;

    public MineralTradeItemCard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

    }

    public void SetItem(MineralListingPrototype proto)
    {
        if (proto.ListingEntityId != null)
        {
            if (proto.Name != null)
                MaterialName.Text = Loc.GetString(proto.Name);

            MaterialPrice.Text = proto.Price.ToString();

            _materialInstance = _entMan.SpawnEntity(proto.ListingEntityId, MapCoordinates.Nullspace);
            MaterialView.SetEntity(_materialInstance);

            if (CheckoutCard)
            {
                BuyButton.Visible = false;
                SellButton.Visible = false;
            }

            BuyButton.OnPressed += (_) =>
            {
                OnBuy ?.Invoke(proto.ID);
            };

            SellButton.OnPressed += (_) =>
            {
                OnSell ?.Invoke(proto.ID);
            };
        }
    }
}
