using Content.Client.Cargo.Systems;
using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.MineralTrade.Protos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MineralTrade.UI;

[GenerateTypedNameReferences]
public sealed partial class MineralTradeTerminal : FancyWindow
{
    public Action<string>? AddToCart;
    public Action<List<MineralListingPrototype>>? CartCheckout;

    public MineralTradeTerminal()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void PopulateMaterialList(List<MineralListingPrototype> listingPrototypes)
    {
        TradeCardsList.RemoveAllChildren();

        foreach (var listing in listingPrototypes)
        {
            var card = new MineralTradeItemCard();
            card.SetItem(listing);

            card.OnBuy += s =>
            {
                AddToCart?.Invoke(s);
            };

            TradeCardsList.AddChild(card);
        }
    }

    public void PopulateCheckoutList(List<MineralListingPrototype> listingPrototypes)
    {
        foreach (var listing in listingPrototypes)
        {
            var card = new MineralTradeItemCard();
            card.SetItem(listing);

            CheckoutButton.OnPressed += _ => CartCheckout?.Invoke(listingPrototypes);

            CheckoutList.AddChild(card);
        }
    }

    public void UpdateBank(int points)
    {
        CargoBank.Text = points.ToString();
    }
}

