- type: entity
  id: Thermoelectricgenerator
  parent: BaseMachineCircuitboard
  name: термоэлектрический генератор (машинная плата)
  description: Печатная плата для термоэлектрического генератора.
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: TegCenter
    stackRequirements:
      Manipulator: 4
      Steel: 5

- type: entity
  id: ThermoelectricgeneratorTurbine
  parent: BaseMachineCircuitboard
  name: циркуляционный насос (машинная плата)
  description: Печатная плата для циркуляционного насоса термоэлектрического генератора.
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: TegCirculator
    stackRequirements:
      Manipulator: 5
      Steel: 5
      Gold: 1

- type: entity
  id: ThrusterShuntingMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: shunting thruster machine board
  components:
  - type: MachineBoard
    prototype: ThrusterShunting
    stackRequirements:
      Manipulator: 1
      Steel: 2
  - type: Tag
    tags:
    - ThrusterShuntingMachineCircuitboard

- type: entity
  id: ThrusterBigLeftMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: big thruster machine board (left)
  components:
  - type: MachineBoard
    prototype: ThrusterBigLeft
    stackRequirements:
      Manipulator: 2
      Steel: 3

- type: entity
  id: ThrusterBigRightMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: big thruster machine board (right)
  components:
  - type: MachineBoard
    prototype: ThrusterBigRight
    stackRequirements:
      Manipulator: 2
      Steel: 3

- type: entity
  id: ThrusterBigCenterMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: big thruster machine board (center)
  components:
  - type: MachineBoard
    prototype: ThrusterBigCenter
    stackRequirements:
      Manipulator: 6
      Steel: 10

- type: entity
  id: PdaIdPainterMachineCircuitboard
  parent: BaseMachineCircuitboard
  components:
  - type: MachineBoard
    prototype: ComputerPdaIdPainter
    stackRequirements:
      Manipulator: 7
