using Content.Shared.CCVar;
using Content.Shared.SS220.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Administration.UI.Tabs.RoundTab
{
    [GenerateTypedNameReferences]
    public sealed partial class RoundTab : Control
    {
        [Dependency] private readonly IConfigurationManager _config = default!;
        public RoundTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _config.OnValueChanged(CCVars220.DelayEnabled, StateChanged, true);
            Delay.OnPressed += ButtonClicked;
        }

        //SS220-Delay-button-admin-panel-begin
        private void StateChanged(bool value)
        {
            Delay.Pressed = value;
        }

        private void ButtonClicked(BaseButton.ButtonEventArgs args)
        {
            Delay.Pressed = _config.GetCVar(CCVars220.DelayEnabled);
        }

        protected override void Deparented()
        {
            base.Deparented();


            _config.UnsubValueChanged(CCVars.OocEnabled, StateChanged);
        }
        //SS220-Delay-button-admin-panel-end
    }
}
