- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 180000 # 50h
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 54000 # 15h
  - !type:RoleTimeRequirement
      role: JobChemist
      time: 54000 #15 h

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 360000 # 100h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 180000 # 50h
  # finally WYCI
